### ISSUE TITLE
Unsupported compression method for this build

### ISSUE THREAD

**Issue by falcon0911** [3Dpass/3DP#100]
Version: 3.1.0-7fe9871-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:695:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:582:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/panicking.rs:578:5
   5: core::panicking::panic_fmt
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/core/src/panicking.rs:67:14
   6: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   7: sc_client_db::utils::read_db
   8: sc_client_db::utils::read_header
   9: <sc_client_db::BlockchainDb<Block> as sp_blockchain::backend::HeaderBackend<Block>>::header
  10: sc_consensus_poscan::PowBlockImport<B,I,C,S,Algorithm,CAW,CIDP,AccountId,BlockNumber>::update_cache
  11: <sc_consensus_poscan::PowBlockImport<B,I,C,S,Algorithm,CAW,CIDP,AccountId,BlockNumber> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  12: <alloc::boxed::Box<dyn sc_consensus::block_import::BlockImport<B>+Error = sp_consensus::error::Error+Transaction = Transaction+core::marker::Sync+core::marker::Send> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closure}}
  13: <&mut F as core::future::future::Future>::poll
  14: sc_consensus::import_queue::basic_queue::BlockImportWorker<B>::new::{{closure}}
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  17: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  19: tokio::park::thread::CachedParkThread::block_on
  20: tokio::runtime::handle::Handle::block_on
  21: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1985:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/alloc/src/boxed.rs:1985:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/521f4dae1bdf7fe9cf9436ecef9ee7c7442708bf/library/std/src/sys/unix/thread.rs:108:17
  28: <unknown>
  29: <unknown>

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "Not implemented: Unsupported compression method for this build" } }', /home/runner/.cargo/git/checkouts/substrate-7e08433d4c370a21/b0777b4/primitives/database/src/kvdb.rs:29

This is a bug. Please report it at:

        https://github.com/3Dpass/3DP/issues

**Comment by fedosov** [comment]
@mishk could you please take a look
